# Generated by Django 6.0.5 on 2026-05-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='年级')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='学科')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.grade', verbose_name='年级')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.subject', verbose_name='学科')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_at'],
            },
        ),
    ]
