# Generated by Django 6.0.5 on 2026-05-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='向量 (32维)'),
        ),
    ]
