# Generated by Django 6.0.5 on 2026-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_article_likes'),
        ('qa', '0009_label_question_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='articles', to='qa.label', verbose_name='标签'),
        ),
    ]
