# Generated by Django 6.0.5 on 2026-06-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_article_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.grade', verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.subject', verbose_name='学科'),
        ),
    ]
