# Generated by Django 6.0.5 on 2026-06-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_alter_article_grade_alter_article_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_translated',
            field=models.TextField(blank=True, verbose_name='内容译文'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_lang',
            field=models.CharField(blank=True, max_length=2, verbose_name='原文语言'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_translated',
            field=models.CharField(blank=True, max_length=400, verbose_name='标题译文'),
        ),
    ]
