version: "3.9"

services:
  backend:
    build: .
    container_name: shsid-backend
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=OpenSHSID_backend.settings
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: shsid-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
