# Generated by Django 6.0.5 on 2026-07-07 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subbar',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_subbars', to=settings.AUTH_USER_MODEL, verbose_name='吧务'),
        ),
        migrations.AlterField(
            model_name='subbar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subbars', to=settings.AUTH_USER_MODEL, verbose_name='吧主'),
        ),
    ]
