"""
Django settings for OpenSHSID_backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# 中央配置：所有可调配置集中在项目根 config.json（密钥用环境变量注入，见 config_loader.py）
from OpenSHSID_backend.config_loader import cfg

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = cfg['django']['secret_key']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = cfg['django']['debug']

ALLOWED_HOSTS = cfg['django']['allowed_hosts']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'qa',
    'knowledge',
    'accounts',
    'chat',
    'notifications',
    'crawler',
    'postbar',
]

# LinkedClassroom credentials (config.json 中配置，密钥走环境变量注入)
LINKEDCLASSROOM_USERNAME = cfg['django']['linkedclassroom']['username']
LINKEDCLASSROOM_PASSWORD = cfg['django']['linkedclassroom']['password']

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OpenSHSID_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenSHSID_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': cfg['django']['database']['engine'],
        'NAME': BASE_DIR / cfg['django']['database']['name'],
        'OPTIONS': {
            # 锁等待（配合 signals.py 的 WAL/busy_timeout），缓解流式写入并发下的锁冲突
            'timeout': cfg['django']['database']['timeout'],
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = cfg['django']['static_url']
STATIC_ROOT = BASE_DIR / cfg['django']['static_root']

MEDIA_URL = cfg['django']['media_url']
MEDIA_ROOT = BASE_DIR / cfg['django']['media_root']

# CORS - allow React dev server
CORS_ALLOW_ALL_ORIGINS = cfg['django']['cors']['allow_all']  # Dev / Docker only
CORS_ALLOW_CREDENTIALS = cfg['django']['cors']['allow_credentials']

# CSRF - 信任的来源（POST/PUT/DELETE 等不安全请求会校验 Origin）
# 开发：Vite 5173 与 Django 19424；生产域名用环境变量 CSRF_TRUSTED_ORIGINS 追加（逗号分隔）
import os as _os

CSRF_TRUSTED_ORIGINS = list(cfg['django']['csrf_trusted_origins'])
CSRF_TRUSTED_ORIGINS += [
    o.strip() for o in _os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# 模型/OCR 服务地址。OCR 跑在带 GPU 的机器上（Unlimited-OCR），主聊天模型在本机。
# 在 config.json 的 services 段配置，仍可用同名环境变量覆盖。
OCR_SERVICE_URL = cfg['services']['ocr_service_url']
MODEL_SERVICE_URL = cfg['services']['model_service_url']

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'UNAUTHENTICATED_USER': None,
}

# 内容审核：发布文章/问答时禁止包含的违禁词（命中则拒绝发布，大小写不敏感）
# 在 config.json 的 django.blocked_words 中维护
BLOCKED_WORDS = list(cfg['django']['blocked_words'])
