# Generated by Django 6.0.5 on 2026-06-26 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True, verbose_name='课程ID')),
                ('title', models.CharField(max_length=255, verbose_name='课程名称')),
                ('summary', models.TextField(blank=True, verbose_name='课程简介')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='章节名称')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='章节链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='crawler.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modtype', models.CharField(blank=True, max_length=50, verbose_name='类型')),
                ('cmid', models.CharField(blank=True, max_length=20, verbose_name='CMID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='标题')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='链接')),
                ('restricted', models.BooleanField(default=False, verbose_name='受限')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crawler.section', verbose_name='章节')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['order'],
            },
        ),
    ]
