# Generated by Django 6.0.5 on 2026-06-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='section',
            name='tile_icon',
            field=models.CharField(blank=True, max_length=60, verbose_name='图标类名'),
        ),
    ]
