# Generated by Django 6.0.5 on 2026-06-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='qa.answer', verbose_name='回复目标'),
        ),
    ]
