# Generated by Django 6.0.5 on 2026-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_answer_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='questions', to='qa.label', verbose_name='标签'),
        ),
    ]
