# Generated by Django 6.0.5 on 2026-06-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_label_question_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_streaming',
            field=models.BooleanField(default=False, verbose_name='生成中'),
        ),
    ]
