# Generated by Django 6.0.5 on 2026-06-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_answer_is_streaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_translated',
            field=models.TextField(blank=True, verbose_name='内容译文'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_lang',
            field=models.CharField(blank=True, max_length=2, verbose_name='原文语言'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_translated',
            field=models.CharField(blank=True, max_length=400, verbose_name='标题译文'),
        ),
    ]
